rtabmap:
  ros__parameters:
    
    # ============ FRAME IDs ============
    frame_id: base_link
    odom_frame_id: odom
    map_frame_id: map
    
    # ============ SUBSCRIPTIONS ============
    # We'll use RGB-D mode with the D435i
    subscribe_depth: true
    subscribe_rgb: true
    subscribe_scan: true           # Use RPLidar S3
    subscribe_scan_cloud: false
    subscribe_rgbd: false
    
    # Number of cameras
    rgbd_cameras: 1
    
    # ============ APPROX SYNC ============
    # Important for cross-network communication
    approx_sync: true
    
    # ============ QoS ============
    qos: 0  # Use SYSTEM_DEFAULT
    queue_size: 10
    
    # ============ WAIT FOR TRANSFORM ============
    wait_for_transform: 0.2
    wait_imu_to_init: false
    
    # ============ DATABASE ============
    database_path: "~/.ros/rtabmap_leo.db"
    
    # ============ SLAM MODE ============
    Mem/IncrementalMemory: true     # SLAM mode (set false for localization)
    Mem/InitWMWithAllNodes: false
    
    # ============ ODOMETRY ============
    # Use wheel odometry from Leo (more reliable than visual)
    odom_sensor_sync: false
    
    # ============ REGISTRATION ============
    # How scans are matched
    Reg/Strategy: 1                 # 0=Visual, 1=ICP, 2=Visual+ICP
    Reg/Force3DoF: true            # Assume planar movement (good for wheeled robot)
    
    # ============ ICP PARAMETERS (for lidar) ============
    Icp/MaxTranslation: 0.2        # 20cm max translation between scans
    Icp/MaxRotation: 0.785         # 45° max rotation
    Icp/VoxelSize: 0.05           # 5cm voxel downsampling
    Icp/MaxCorrespondenceDistance: 0.1
    Icp/PM: true                   # Use libpointmatcher
    Icp/PMOutlierRatio: 0.85
    Icp/CorrespondenceRatio: 0.2
    
    # ============ VISUAL ODOMETRY ============
    Vis/MinInliers: 15
    Vis/MaxDepth: 4.0             # Ignore depth > 4m
    Vis/CorType: 0                # 0=Features Matching
    Vis/FeatureType: 6            # 6=GFTT (good for texture-less environments)
    Vis/MaxFeatures: 400
    
    # ============ OPTIMIZATION ============
    Optimizer/Strategy: 1          # 1=g2o
    Optimizer/Epsilon: 0.00001
    Optimizer/Iterations: 100
    Optimizer/Robust: true
    
    RGBD/OptimizeFromGraphEnd: false
    RGBD/OptimizeMaxError: 3.0
    RGBD/ProximityBySpace: true
    RGBD/ProximityPathMaxNeighbors: 10
    
    # When to create new nodes
    RGBD/AngularUpdate: 0.05       # 5° rotation
    RGBD/LinearUpdate: 0.05        # 5cm movement
    RGBD/LocalRadius: 5.0          # Local map radius
    
    # ============ LOOP CLOSURE ============
    Mem/RehearsalSimilarity: 0.30
    Mem/STMSize: 10
    Rtabmap/TimeThr: 0            # 0=no time limit for loop closure
    Rtabmap/DetectionRate: 1.0    # Process every frame
    Rtabmap/LoopRatio: 0.9
    
    # Loop closure detection
    Kp/MaxFeatures: 400
    Kp/DetectorStrategy: 6        # GFTT
    Kp/RoiRatios: [0.0, 0.0, 0.0, 0.0]
    
    #Bayes/FullPredictionUpdate: 'false'
    
    # ============ 3D MAPPING ============
    Grid/3D: 'true'
    Grid/RayTracing: true
    Grid/CellSize: 0.05           # 5cm cells
    Grid/MaxObstacleHeight: 2.0   # Max obstacle height
    Grid/MinObstacleHeight: 0.1   # Min obstacle height  
    Grid/MaxGroundHeight: 0.0     # Ground level
    Grid/MinGroundHeight: -0.2
    Grid/NormalsSegmentation: true
    Grid/ClusterRadius: 0.1
    Grid/FlatObstacleDetected: true
    Grid/PreVoxelFiltering: true
    Grid/GroundIsObstacle: false
    
    # Use both depth and lidar for mapping
    Grid/FromDepth: true
    Grid/RangeMax: 5.0           # Max range for mapping
    GridGlobal/MinSize: 20.0
    
    # ============ PERFORMANCE ============
    Rtabmap/ImageBufferSize: 1
    Rtabmap/MaxRetrieved: 2
    Rtabmap/PublishRAMUsage: true
    Rtabmap/ComputeRMSE: false
    Rtabmap/SaveWMState: false
    
    # Memory management
    Mem/RecentWmRatio: 0.2
    Mem/ImageKept: false          # Don't keep images in memory (saves RAM)
    Mem/BinDataKept: true
    
    # ============ VISUALIZATION ============
    Grid/NoiseFilteringRadius: 0.05
    Grid/NoiseFilteringMinNeighbors: 5